name: monad-action
description: an action to install and configure monad.
author: Brendan Keane

# Define your inputs here.
inputs:
  version:
    description: monad version to install
    required: true
    default: 'v0.1.4'
  ecr_registry_id:
    description: Configure the ECR registry ID monad will use.
    required: false
  ecr_registry_region:
    description: Configure the ECR registry region monad will use.
    required: false
  iam_permissions_boundary:
    description:
      Name of the IAM permissions boundary monad will apply to managed roles.
    required: false

outputs:

runs:
  using: node20
  main: dist/index.js
